/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zavrsnirad.view;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.ListSelectionModel;
import zavrsnirad.controller.ObradaProizvod;

import zavrsnirad.controller.ObradaRezervacija;
import zavrsnirad.controller.ObradaZaposlenik;
import zavrsnirad.model.Proizvod;
import zavrsnirad.model.ProizvodRezervacije;
import zavrsnirad.model.Rezervacija;
import zavrsnirad.model.Zaposlenik;

import zavrsnirad.util.EdunovaException;
import zavrsnirad.util.Pomocno;


/**
 *
 * @author X
 */
public class ProzorRezervacija extends javax.swing.JFrame {

    
    private ObradaRezervacija obradaRezervacija;
    private ObradaProizvod obradaProizvod;
    
    
    
    
    
    /**
     * Creates new form ProzorRezervacija
     */
    public ProzorRezervacija() {
        initComponents();
        obradaRezervacija=new ObradaRezervacija();
        obradaProizvod=new ObradaProizvod();
        postavke();
        ucitaj();
    }

    
    private void ucitaj(){
        lstProizvodi.setModel(new  EdunovaListModel<>(obradaProizvod.read()));
        lstDolazak.setModel(new EdunovaListModel<>(obradaRezervacija.read()));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstDolazak = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBrojLjudi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnPromjeni = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProizvodi = new javax.swing.JList<>();
        btnTrazi = new javax.swing.JButton();
        txtUvjet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstProizvodiNaRezervaciji = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tyKolicina = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnDodajProizvod = new javax.swing.JButton();
        btnObrisiProizvod = new javax.swing.JButton();
        cmbZaposlenik = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dpDatumDolaska = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstDolazak.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDolazakValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDolazak);

        jLabel1.setText("Ime :");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Broj Ljudi:");

        jLabel4.setText("Email:");

        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel5.setText("Datum dolaska:");

        jScrollPane2.setViewportView(lstProizvodi);

        btnTrazi.setText("Traži");
        btnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraziActionPerformed(evt);
            }
        });

        jLabel7.setText("Proizvodi");

        lstProizvodiNaRezervaciji.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProizvodiNaRezervacijiValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstProizvodiNaRezervaciji);

        tyKolicina.setColumns(20);
        tyKolicina.setRows(5);
        tyKolicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tyKolicinaKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(tyKolicina);

        jLabel8.setText("Količina");

        btnDodajProizvod.setText("<");
        btnDodajProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajProizvodActionPerformed(evt);
            }
        });

        btnObrisiProizvod.setText(">");
        btnObrisiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiProizvodActionPerformed(evt);
            }
        });

        jLabel9.setText("Zaposlenik");

        jLabel10.setText("Proizvodi na rezervaciji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIme, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbZaposlenik, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dpDatumDolaska, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBrojLjudi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(112, 112, 112))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPromjeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnObrisi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTrazi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDodajProizvod)
                            .addComponent(btnObrisiProizvod))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dpDatumDolaska, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbZaposlenik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBrojLjudi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPromjeni)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addGap(70, 70, 70))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnDodajProizvod)
                        .addGap(55, 55, 55)
                        .addComponent(btnObrisiProizvod))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTrazi)
                                    .addComponent(txtUvjet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lstDolazakValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDolazakValueChanged
         if (evt.getValueIsAdjusting() || lstDolazak.getSelectedValue() == null) {
            return;
        }
        obradaRezervacija.setEntitet(lstDolazak.getSelectedValue());
        
        popuniView();
    }//GEN-LAST:event_lstDolazakValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        obradaRezervacija.setEntitet(new Rezervacija());
        popuniModel();
        try {
            obradaRezervacija.create();
            ucitaj();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        if ( lstDolazak.getSelectedValue()==null ||
                obradaRezervacija.getEntitet() == null) {
            JOptionPane.showMessageDialog(rootPane, 
                    "Prvo odaberite grupu");
            return;
        }
        popuniModel();

        try {
            obradaRezervacija.update();
            ucitaj();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane,
                    e.getPoruka());
        }
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        if(obradaRezervacija.getEntitet()==null){
            JOptionPane.showMessageDialog(rootPane, "Prvo odaberite grupu");
            return;
        }
        
        popuniModel();
        try {
            obradaRezervacija.delete();
            //pocistiView();
            ucitaj();
        } catch (EdunovaException e) {
            JOptionPane.showMessageDialog(rootPane, e.getPoruka());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraziActionPerformed
        
        List<Proizvod> proizvodi = 
                obradaProizvod
                        .read(txtUvjet.getText().trim());

        
        
        lstProizvodi.setModel(
                new EdunovaListModel<>(proizvodi)
        );
        if(proizvodi.isEmpty()){
            txtUvjet.requestFocus();
            return;
        }
        try {
            lstProizvodi.setSelectedIndex(0);
        } catch (Exception e) {
        }
        //lstClanoviGrupe.requestFocus();
    }//GEN-LAST:event_btnTraziActionPerformed

    private ProizvodRezervacije kreirajProiz( Proizvod p,Rezervacija r,String n){
        ProizvodRezervacije pr=new ProizvodRezervacije();
         pr.setProizvod(p);
         pr.setRezervacija(r);
         pr.setKolicina(n);
         
        return pr;
    }
    
    
    
    
     private void dodajProizvod(){
       
        if(lstProizvodi.getSelectedValue()==null){
            return;
        }
        
        
        DefaultListModel<ProizvodRezervacije> proizvodiRezervacije = (DefaultListModel<ProizvodRezervacije>) lstProizvodiNaRezervaciji.getModel();
       
        
        for(int i=0;i<proizvodiRezervacije.getSize();i++){
            if(proizvodiRezervacije.get(i).getProizvod().getSifra().equals(
                    lstProizvodi.getSelectedValue().getSifra())){
                JOptionPane.showMessageDialog(rootPane, 
                        "Polaznik je već dodan na grupu");
                return;
            }
        }
        
         
        
        
    }
      
    


    
    
    
    
    
    
    
    
    private void btnDodajProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajProizvodActionPerformed

        
        DefaultListModel<ProizvodRezervacije> pr = (DefaultListModel<ProizvodRezervacije>) lstProizvodiNaRezervaciji.getModel();
        
        if(pr==null){
            pr = new DefaultListModel<>() ;
        }
        
        ProizvodRezervacije pe;
        for(Proizvod p : lstProizvodi.getSelectedValuesList()){
            pe=new ProizvodRezervacije();
            pe.setProizvod(p);
            pe.setRezervacija(obradaRezervacija.getEntitet());
            pe.setKolicina(tyKolicina.getText());
            pr.addElement(pe);
        }
        lstProizvodiNaRezervaciji.setModel(pr);
        lstProizvodiNaRezervaciji.repaint();
        
    }//GEN-LAST:event_btnDodajProizvodActionPerformed

    private void lstProizvodiNaRezervacijiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProizvodiNaRezervacijiValueChanged
        if(evt.getValueIsAdjusting() || lstProizvodiNaRezervaciji.getSelectedValue()==null){
            return;
        }
          tyKolicina.setText(
                lstProizvodiNaRezervaciji
                        .getSelectedValue()
                        .getKolicina()
        );
    }//GEN-LAST:event_lstProizvodiNaRezervacijiValueChanged

    private void btnObrisiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiProizvodActionPerformed
         DefaultListModel<ProizvodRezervacije> m=(DefaultListModel<ProizvodRezervacije>) lstProizvodiNaRezervaciji.getModel();
        for(ProizvodRezervacije c:lstProizvodiNaRezervaciji.getSelectedValuesList()){
            m.removeElement(c);
            lstProizvodiNaRezervaciji.repaint();
        }
    }//GEN-LAST:event_btnObrisiProizvodActionPerformed

    private void tyKolicinaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tyKolicinaKeyTyped
        if (lstProizvodiNaRezervaciji.getSelectedValue() == null) {
            return;
        }
        var s = tyKolicina .getText()
                + evt.getKeyChar();
//       for(int i=0;i<s.length();i++){
//           System.out.println((int)s.charAt(i) + ": " +
//                   s.charAt(i));
//       }
        s = s.replace((char) 22, (char) 0);
        lstProizvodiNaRezervaciji
                .getSelectedValue()
                .setKolicina(s);
    
    }//GEN-LAST:event_tyKolicinaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajProizvod;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnObrisiProizvod;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JButton btnTrazi;
    private javax.swing.JComboBox<Zaposlenik> cmbZaposlenik;
    private com.github.lgooddatepicker.components.DatePicker dpDatumDolaska;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<Rezervacija> lstDolazak;
    private javax.swing.JList<Proizvod> lstProizvodi;
    private javax.swing.JList<ProizvodRezervacije> lstProizvodiNaRezervaciji;
    private javax.swing.JTextField txtBrojLjudi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtUvjet;
    private javax.swing.JTextArea tyKolicina;
    // End of variables declaration//GEN-END:variables

    private void popuniView() {
        var e =obradaRezervacija.getEntitet();
        
        dpDatumDolaska.setText(e.getDolazakRezervacije().toString());
        txtIme.setText(e.getIme());
        txtPrezime.setText(e.getPrezime());
        txtEmail.setText(e.getEmail());
        txtBrojLjudi.setText(e.getBrojLjudi().toString());
         Date input = e.getDolazakRezervacije();
        LocalDate date = input.toInstant()
                .atZone(ZoneId.systemDefault()).toLocalDate();
        dpDatumDolaska.setDate(date);
        
        cmbZaposlenik.setSelectedItem(e.getZaposlenik());
        
         lstProizvodiNaRezervaciji.setModel(
                new EdunovaListModel<>(e.getProizvodRezervacije()));
        
        
        
    }


    private void popuniModel() {
        
        var s=obradaRezervacija.getEntitet();
       
        s.setDolazakRezervacije(new Date());
        s.setIme(txtIme.getText());
        s.setPrezime(txtPrezime.getText());
        s.setEmail(txtEmail.getText());
        try {
            s.setBrojLjudi(Integer.parseInt(txtBrojLjudi.getText()));
        } catch (Exception e) {
            s.setBrojLjudi(10);
        }
        
         s.setDolazakRezervacije(dpDatumDolaska.getDate() != null
                ? Date.from(dpDatumDolaska.getDate()
                        .atStartOfDay()
                        .atZone(ZoneId.systemDefault())
                                 .toInstant()
                ) : null
        );
         
         
         s.setZaposlenik((Zaposlenik) cmbZaposlenik.getSelectedItem());
         
         
        DefaultListModel<ProizvodRezervacije> m
                = (DefaultListModel<ProizvodRezervacije>) lstProizvodiNaRezervaciji.getModel();

        List<ProizvodRezervacije> noviProizvodi = new ArrayList<>();
        for (int i = 0; i < m.getSize(); i++) {
            noviProizvodi.add(m.getElementAt(i));
        }
        obradaRezervacija.setNoviProizvodi(noviProizvodi);
         
         
    }
        
   
    

    private void postavke() {
        lstDolazak.setModel(new DefaultListModel<>());
        prilagodiDatepicker();
        ucitajZaposlenike();
    }

    private void prilagodiDatepicker() {
        DatePickerSettings dps
                = new DatePickerSettings(new Locale("hr", "HR"));
        dps.setFormatForDatesCommonEra(Pomocno.FORMAT_DATUMA);
        dps.setTranslationClear("Očisti");
        dps.setTranslationToday("Danas");
        dpDatumDolaska.setSettings(dps);
    }

    private void ucitajZaposlenike() {
        
         DefaultComboBoxModel<Zaposlenik> z
                = new DefaultComboBoxModel<>();
        z.addAll(new ObradaZaposlenik().read());
        cmbZaposlenik.setModel(z);
        
        
    }
}
